# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: E2E

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
 newman:
    name: Run Newman test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install newman
      run: |
       npm install -g newman
    - name: Run POSTMAN collection
      run: |
       newman run ./Backend/Collection/TODOIST.postman_collection.json -e ./Todoist/backend/envVariables/QA.postman_environment.json
     
 windows10_test:
    name: Run Windows 10 Nigthwatch Tests
    runs-on: windows-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v1
      - name: Install Nigthwatch BrowserStack plugin
        run: npm install nightwatch-browserstack
      - name: Eslint
        run: npm run lint
      - name: BrowserStack
        run: npm run test:browserstackWindows
